### ISSUE TITLE
How can we tell the results from eflips-depot is stable?

### ISSUE THREAD

**Issue by shuyao-guo** [mpm-tu-berlin/eflips-depot#131]
Regarding the mechanism of schedule copying, there will be 3 kinds of vehicles generated by simulation core, which are:

1. Vehicles serving copied schedules, then original schedules, then copied schedules
2. Vehicles serving at the beginning directly original schedules, then copied schedules (maybe also the other way around, needed further observation)
3. Vehicles only serving copied schedules

How should we evaluate those situations and determine the stable one

**Comment by shuyao-guo** [comment]
After a discussion with @ludgerheide , we have decided:
1. if the vehicle count increase continuously from week 1 to week 3 (which will be found from simulation core figure), it is then an unstable solution.
2. It should be paid attention to when evaluating the quality of solutions from @danialmasoud, whose algorithm generates solutions first, and we check whether the corresponding depot layout produces an increasing/unstable vehicle requirement.

**Comment by ludgerheide** [comment]
We do the simulation foru times now, that should take care of most situations. Doing it better should be moved to "SimCore 2.0"
