### ISSUE TITLE
XLRD not supporting XLSX files anymore

### ISSUE THREAD

**Issue by joe29k** [mpm-tu-berlin/eflips-depot#3]
The `xlrd` package no longer supports .xlsx files. But `eflips/depot/standalone.py` makes use of this module to read .xlsx files, therefore causing crashes if a recent version is used.

(Might be moved to eflips repo after the eflips version eflips_depot uses was transferred there)

**Comment by ludgerheide** [comment]
works now, remove excel stuff later (#67)
